-- Generated by Noctalia. Changes to this output are overwritten on palette changes.
vim.g.colors_name = "noctalia"

local set = vim.api.nvim_set_hl
local none = "NONE"

set(0, "Normal",       { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface.default.hex }}" })
set(0, "NormalFloat",  { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
set(0, "FloatBorder",  { fg = "{{ colors.outline.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
set(0, "CursorLine",   { bg = "{{ colors.surface_container_high.default.hex }}" })
set(0, "CursorLineNr", { fg = "{{ colors.primary.default.hex }}", bold = true })
set(0, "LineNr",       { fg = "{{ colors.outline.default.hex }}" })
set(0, "Visual",       { bg = "{{ colors.primary_container.default.hex }}" })
set(0, "Search",       { fg = "{{ colors.on_tertiary_container.default.hex }}", bg = "{{ colors.tertiary_container.default.hex }}" })
set(0, "IncSearch",    { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}" })
set(0, "Pmenu",        { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
set(0, "PmenuSel",     { fg = "{{ colors.on_primary_container.default.hex }}", bg = "{{ colors.primary_container.default.hex }}", bold = true })
set(0, "StatusLine",   { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}", bold = true })
set(0, "StatusLineNC", { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "{{ colors.surface_variant.default.hex }}" })
set(0, "WinSeparator", { fg = "{{ colors.outline_variant.default.hex }}", bg = none })
set(0, "Comment",      { fg = "{{ colors.on_surface_variant.default.hex }}", italic = true })
set(0, "Constant",     { fg = "{{ colors.tertiary.default.hex }}" })
set(0, "String",       { fg = "{{ colors.terminal_normal_green.default.hex }}" })
set(0, "Identifier",   { fg = "{{ colors.secondary.default.hex }}" })
set(0, "Function",     { fg = "{{ colors.primary.default.hex }}" })
set(0, "Statement",    { fg = "{{ colors.terminal_normal_magenta.default.hex }}", bold = true })
set(0, "PreProc",      { fg = "{{ colors.terminal_normal_cyan.default.hex }}" })
set(0, "Type",         { fg = "{{ colors.terminal_normal_yellow.default.hex }}" })
set(0, "Special",      { fg = "{{ colors.tertiary.default.hex }}" })
set(0, "Error",        { fg = "{{ colors.on_error.default.hex }}", bg = "{{ colors.error.default.hex }}" })
set(0, "DiagnosticError", { fg = "{{ colors.error.default.hex }}" })
set(0, "DiagnosticWarn",  { fg = "{{ colors.terminal_normal_yellow.default.hex }}" })
set(0, "DiagnosticInfo",  { fg = "{{ colors.secondary.default.hex }}" })
set(0, "DiagnosticHint",  { fg = "{{ colors.tertiary.default.hex }}" })
